#include <iostream>
#include <string>
#include <utility>
#include <functional>
#include <tuple>
#include <map>
#include <vector>
#include <algorithm>
#include <stdexcept>
#include <iterator>
#include <cassert>
#include <cmath>
#include <sstream>
#include <unordered_map>
